// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQYNy2pvzWAjpc5Mm77dBtNpS5nT-tYek',
    appId: '1:202103645007:web:aa634ed2f26b012cd7db3a',
    messagingSenderId: '202103645007',
    projectId: 'hallooo-27148',
    authDomain: 'hallooo-27148.firebaseapp.com',
    storageBucket: 'hallooo-27148.firebasestorage.app',
    measurementId: 'G-9Z794NNBTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtY0KrNSvlRHSLuNk-68JctsXGMMrkoN0',
    appId: '1:202103645007:android:9309d248ad78f47bd7db3a',
    messagingSenderId: '202103645007',
    projectId: 'hallooo-27148',
    storageBucket: 'hallooo-27148.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArVHL60qQOK2JUB9PPNFT7BCgVxDiGswo',
    appId: '1:202103645007:ios:9ae8b3ce4dce3f7dd7db3a',
    messagingSenderId: '202103645007',
    projectId: 'hallooo-27148',
    storageBucket: 'hallooo-27148.firebasestorage.app',
    androidClientId: '202103645007-2dkdqqt5v2l1anp7v3clkjmritci2i33.apps.googleusercontent.com',
    iosClientId: '202103645007-oj760hvdsjbdi4bailu09ts6victj2c6.apps.googleusercontent.com',
    iosBundleId: 'com.islington.chatbot',
  );
}
